Fix Make concurrency by first creating OBJDIR (closes #22)
This fixes a bug that would often surface when compiling libbpf-sys as
part of a large project, when MAKEFLAGS=-j16 or similar was set in the
environment:

    error: failed to run custom build command for `libbpf-sys v0.4.0-2`

    Caused by:
      process didn't exit successfully: `/path/to/project/target/release/build/libbpf-sys-69ba8c3c4b118a19/build-script-build` (exit status: 101)
      --- stdout
        MKDIR    staticobjs
        INSTALL  bpf.h libbpf.h btf.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h libbpf_common.h

      --- stderr
      /bin/sh: line 1: /path/to/project/target/release/build/libbpf-sys-3d7d9646259d81be/out/obj/libbpf.pc: No such file or directory
      make: *** [Makefile:102: /path/to/project/target/release/build/libbpf-sys-3d7d9646259d81be/out/obj/libbpf.pc] Error 1
      make: *** Waiting for unfinished jobs....
      thread 'main' panicked at 'assertion failed: status.success()', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-0.4.0-2/build.rs:46:9

I discovered this in building the AUR package below-git
<https://aur.archlinux.org/packages/below-git/#comment-827832>, because
I have `MAKEFLAGS=-j16` set in my /etc/makepkg.conf—a fairly common
thing to do. After isolating the makepkg stuff from it, I confirmed
that taking a clean clone of below (which depends on libbpf-sys) and
running `MAKEFLAGS=-j16 cargo build --release` would *normally* fail.
Various factors would make it more or less likely to fail.

The source of the bug is that when `make install` is invoked, the path
contained in the environment variable OBJDIR doesn’t yet exist.

Most of the time, OBJDIR would be created incidentally (by
`mkdir -p $(OBJDIR)/staticobjs`), but once you introduced sufficient
concurrency at the Make level *and* load the CPU up pretty heavily
(which Cargo delights in doing!), it’s possible for the libbpf.pc rule
to try to write to $(OBJDIR)/libbpf.pc before the directory gets
created. (The staticobjs is doing an echo then a mkdir, whereas the .pc
recipe goes straight to its sh instance trying to create the file, so
it’s unsurprising that in the right conditions it’ll get there first; in
fact, the more I think about it the more I’m surprised that it *ever*
succeeds when concurrency is enabled.)

Solution: create that OBJDIR directory before invoking `make`.

(You could also instruct the Makefile in how to create $(OBJDIR) itself,
like it does with staticobjs, but requiring that OBJDIR exist already
seems reasonable to me.)

Signed-off-by: Alex Forster <aforster@cloudflare.com>